### ISSUE TITLE
在Android Studio 2.1.2 安装报以下错误

### ISSUE THREAD

**Issue by deliangliao** [zhonghanwen/AndroidProguardPlugin#4]
Plugin 'com.zhw.tgnet.android.AndroidProGuard' failed to initialize and will be disabled.  Please restart Android Studio.

com.intellij.diagnostic.PluginException: com/zhy/http/okhttp/https/HttpsUtils : Unsupported major.minor version 51.0 [Plugin: com.zhw.tgnet.android.AndroidProGuard]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at com.zhw.proguard.AndroidComponent.<init>(AndroidComponent.java:35)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
    at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
    at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:495)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:123)
    at com.intellij.openapi.application.impl.ApplicationImpl.access$801(ApplicationImpl.java:91)
    at com.intellij.openapi.application.impl.ApplicationImpl$12.run(ApplicationImpl.java:497)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:512)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:107)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:455)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:447)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:197)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:52)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.UnsupportedClassVersionError: com/zhy/http/okhttp/https/HttpsUtils : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:260)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:256)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:225)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:124)
    ... 43 more

**Comment by zhonghanwen** [comment]
@deliangliao 你的JDK版本号多少？

**Comment by deliangliao** [comment]
1.8
<img src="http://myfish.qiniudn.com/markdown/1465719030124.png" width="475"/>

**Comment by zhonghanwen** [comment]
@deliangliao 我将我的换成你这个版本，但是还是可以安装！![](http://zhuangbi.idagou.com/i/2016-02-22-ebdcac76b11ed66c295ef0b30e0828be.jpg)

**Comment by deliangliao** [comment]
@zhonghanwen 我也纳闷。mac环境下 Android Studio 2.1.2版本
<img src="http://myfish.qiniudn.com/markdown/1465724012911.png" width="739"/>
改天试试全新环境再装下试试，感谢！

**Comment by zhonghanwen** [comment]
@deliangliao 喔~原来你的是Mac的，这个我要测试一下，因为我使用的Windows的~

**Comment by zhonghanwen** [comment]
@deliangliao 我在Mac测试了一下，发现不会出现你这个问题！我使用的JDK是官方最新的，亲测可以使用~这个问题估计是JDK版本的导致的~ 
![image](https://cloud.githubusercontent.com/assets/12220537/15995688/d6030f98-3151-11e6-894e-8cf7f0d25e57.png)

**Comment by uditunpluged** [comment]
Facing the same problem.... I am on mac too and gives me following error while installation:

com.intellij.diagnostic.PluginException: com/zhy/http/okhttp/https/HttpsUtils : Unsupported major.minor version 51.0 [Plugin: com.zhw.tgnet.android.AndroidProGuard]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:130)
    at

**Comment by zhonghanwen** [comment]
@uditunpluged may be you JDK version problem...I try to slove the bug~

**Comment by f-evil** [comment]
Same error.

**Comment by gzfgeh** [comment]
same error

**Comment by DeKaiju** [comment]
+1

**Comment by kingtami** [comment]
@zhonghanwen 你好,请问是系统JDK版本,还是AS里面的JDK版本?你说的官方是Oracle官方还是AS自带的?

**Comment by zhonghanwen** [comment]
@kingtami Oracle官方的

**Comment by kingtami** [comment]
@deliangliao @uditunpluged @f-evil @gzfgeh 
mac os users please refer to this, install jdk 1.8, change jvmVersion to 1.8, it works for me:
https://xinyustudio.wordpress.com/2016/05/04/install-statistics-plugin-for-androidstudio-crash-and-troubleshooting/

**Comment by zhonghanwen** [comment]
@kingtami 感谢您的解决~

**Comment by 790396054** [comment]
same error, mac 环境 AS2.1.2
